title: Stackbit Ampersand Theme
baseURL: /
params:
  footer:
    content: '&copy; Add Homonym PBC'
    has_social: false
    links: []
  header:
    has_nav: false
    logo_img: /images/artboard-1.png
    title: The Hawaii Independent
  layout_style: list
disableKinds:
  - RSS
